### ISSUE TITLE
Surefire Fork Build Failure

### ISSUE THREAD

**Issue by jaredpetersen** [carlossg/docker-maven#90]
Builds using the image tag `3-jdk-10` started failing this morning with the following error:

```
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /builds/sdm/v1.x/kafka-streams-graphdb && /usr/lib/jvm/java-10-openjdk-amd64/bin/java '-javaagent:/builds/sdm/v1.x/kafka-streams-graphdb/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/builds/sdm/v1.x/kafka-streams-graphdb/target/jacoco.exec,excludes=**/Main.*' -jar /builds/sdm/v1.x/kafka-streams-graphdb/target/surefire/surefirebooter13709075166013607727.jar /builds/sdm/v1.x/kafka-streams-graphdb/target/surefire 2018-10-25T15-33-21_667-jvmRun1 surefire8226542468175712166tmp surefire_01377591845093324914tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /builds/sdm/v1.x/kafka-streams-graphdb && /usr/lib/jvm/java-10-openjdk-amd64/bin/java '-javaagent:/builds/sdm/v1.x/kafka-streams-graphdb/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/builds/sdm/v1.x/kafka-streams-graphdb/target/jacoco.exec,excludes=**/Main.*' -jar /builds/sdm/v1.x/kafka-streams-graphdb/target/surefire/surefirebooter13709075166013607727.jar /builds/sdm/v1.x/kafka-streams-graphdb/target/surefire 2018-10-25T15-33-21_667-jvmRun1 surefire8226542468175712166tmp surefire_01377591845093324914tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:671)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1194)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1022)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:868)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project kafka-streams-graphdb: There are test failures.
```

The image was updated about 3 hours ago but I don't see a change in this repository at all, so I'm not sure what's going on there.

Changing these builds to use `3-jdk-11` allows for tests to run again and the builds pass.

I don't know whether or not this situation is popping up again: #73. The symptoms are the exact same.

**Comment by KevinToala** [comment]
In my AWS codebuild, I have the same error today

**Comment by adamrehill** [comment]
Our team had the same issue when using 3.5-jdk-10

We had to use 3.5.3-jdk-10 to get the tests running again

**Comment by queer** [comment]
Seeing the exact same thing as @adamrehill; going `3.5-jdk-10` -> `3.5.3-jdk-10` fixed it for me.

**Comment by marazt** [comment]
+1 same for us.

**Comment by muratozkan** [comment]
I think this is more related with the OpenJDK 10 base image that `3.5.4-jdk-10` uses as a base image. I used Maven Wrapper with `openjdk:10-jdk`, using both maven versions `3.5.3` and `3.5.4`. Both throw the same error.

As a solution, I am using the `3.5-jdk-10` (with Maven `3.5.4`), overriding `surefire` and `failsafe` plugin configurations: 

```
    <plugin>
        <artifactId>maven-failsafe-plugin</artifactId>
        <configuration>
            <useSystemClassLoader>false</useSystemClassLoader>
        </configuration>
    </plugin>
    <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
            <useSystemClassLoader>false</useSystemClassLoader>
        </configuration>
    </plugin>

```

**Comment by akewea** [comment]
Got the same error with `3-jdk-8`... 
@muratozkan solution worked for me.

**Comment by TamasNeumer** [comment]
Same here with `3-jdk-8`. Specifying `<useSystemClassLoader>false</useSystemClassLoader>` for **both** surfire and failsafe solved the problem. Thanks @muratozkan !

**Comment by carlossg** [comment]
I'll take this is related to #92

**Comment by fedepia** [comment]
We have the same error using image `maven:3.6.0-jdk-8`.

In order to fix this issue we have added below workaround:
```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <forkCount>0</forkCount>
                </configuration>
            </plugin>
```

**Comment by magiccrafter** [comment]
with image `maven:3.6.0-jdk-8` the following works like charm
```
<plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-surefire-plugin</artifactId>
   <version>3.0.0-M3</version>
   <configuration>
       <useSystemClassLoader>false</useSystemClassLoader>
   </configuration>
</plugin>
```

**Comment by mxxk** [comment]
After running into this issue, I only had to apply `<useSystemClassLoader>false</useSystemClassLoader>` to `maven-surefire-plugin` to remedy the Surefire problem (i.e. exactly what @magiccrafter commented above). However, setting the same property on `maven-failsafe-plugin` (as suggested by @muratozkan earlier in the thread), seems to have no effect.

Using `<forkCount>0</forkCount>` (per advice of @fedepia) is another workaround, but surrenders the benefits of executing tests in an forked, isolated environment from the main Maven process. (See: https://stackoverflow.com/a/3186620)

In case it helps diagnose this further, after Maven terminated with "The forked VM terminated without properly saying goodbye", it left a file in the `target/surefire-reports` directory:

```
$ cat target/surefire-reports/2019-02-15T20-04-23_904.dumpstream
# Created at 2019-02-15T20:04:24.258
Error: Invalid or corrupt jarfile /app/target/surefire/surefirebooter15847623166706412603.jar
```

However, the `surefirebooter*.jar` file is only temporarily created then removed, so I could not inspect it. See: https://stackoverflow.com/questions/54716967/maven-tests-fail-with-forked-vm-terminated-in-docker

**Comment by azachar** [comment]
Well, I just did `sudo apt-get upgrade -y` to get latest JDK patches and it works out of the box. (My base image is `maven:3.6-jdk-8-slim`)

**Comment by carlossg** [comment]
fixed upstream

**Comment by Tibor17** [comment]
@mxxk 
Use debug mode in Maven `mvn -X test` which keeps the file `/app/target/surefire/surefirebooter15847623166706412603.java` not deleted. Did you use Docker? What JDK version use used? Pls reply to [JIRA](https://issues.apache.org/jira/projects/SUREFIRE/) or to our [mailing list](https://maven.apache.org/mailing-lists.html). We still have these issues but I doubt that your concrete is related to Surefire issue. It looks like a problem with permissions in `/app/target/surefire`.
